---
  - name: install dependencies
    apt: pkg={{ item }} state=latest
    with_items:
      - git
      - git-core
      - zsh

  - name: Clone-oh-my-zsh repo
    git:
      repo=https://github.com/robbyrussell/oh-my-zsh.git
      dest=/home/{{user}}/.oh-my-zsh
      update=no

  - name: Chown oh-my-zsh folder to the current user
    file:
      path=/home/{{user}}/.oh-my-zsh/
      state=directory
      owner={{user}}
      group={{user}}

  - name: Create conf folder in homedir
    file:
      path=/home/{{user}}/conf/
      state=directory
      owner={{user}}
      group={{user}}

  - name: deploy .zshrc from template
    template:
      src=zshrc.j2
      dest=/home/{{user}}/conf/zshrc
      owner={{user}}
      group={{user}}

  - name: remove standard zshrc
    file:
      path=/home/{{user}}/.zshrc
      state=absent

  - name: Symlink .zshrc
    file:
      path=/home/{{user}}/.zshrc
      src=/home/{{user}}/conf/zshrc
      state=link
      owner={{user}}
      group={{user}}

  - name: Set zsh as default shell
    user:
      name={{user}}
      shell=/bin/zsh
