---

- name: provision the development server
  hosts: all
  sudo: yes
  vars:
    user: vagrant
  pre_tasks:
    - name: update apt cache
      apt:
        update_cache=yes
        cache_valid_time=3600
    - name: upgrade (safe) all packages
      apt: upgrade=safe
    - name: install or update prerequisite packages
      apt:
        name={{item}}
        state=present
      with_items:
        - aptitude
        - vim-nox
        - htop
    - name: ensure language pack is installed
      apt: name=language-pack-en state=present

    - name: determine whether oh-my-zsh needs to be installed
      stat: path=/home/{{user}}/.oh-my-zsh
      register: myzsh


  roles:
    - { role: oh-my-zsh, when: not myzsh.stat.exists }
    - { role: leiningen }
    - { role: database }
